import type { Product, Category } from '../types'

export const MOCK_PASTRIES: Product[] = [
    {
        id: 1001,
        title: 'Triple Chocolate Heaven',
        description: 'Layers of dark, milk, and white chocolate mousse on a flourless chocolate sponge. Finished with a rich cocoa glaze.',
        price: 14.99,
        discountPercentage: 10,
        rating: 4.8,
        stock: 12,
        brand: 'TMPASTAHOUSE',
        category: 'Signature Cakes',
        thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800'],
        tags: ['chocolate', 'cake', 'sweet'],
    },
    {
        id: 1002,
        title: 'Strawberry Dream Sponge',
        description: 'Classic Victoria sponge with fresh organic strawberries and hand-whipped vanilla cream.',
        price: 12.50,
        discountPercentage: 0,
        rating: 4.9,
        stock: 8,
        brand: 'TMPASTAHOUSE',
        category: 'Signature Cakes',
        thumbnail: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=800'],
        tags: ['strawberry', 'cake', 'fresh'],
    },
    {
        id: 1003,
        title: 'Pistachio Cream Croissant',
        description: 'Twice-baked butter croissant filled with homemade pistachio Frangipane and topped with crushed Sicilian pistachios.',
        price: 5.75,
        discountPercentage: 15,
        rating: 4.7,
        stock: 24,
        brand: 'TMPASTAHOUSE',
        category: 'Pastries',
        thumbnail: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800'],
        tags: ['croissant', 'pistachio', 'pastry'],
    },
    {
        id: 1004,
        title: 'Rainbow Macarons Gift Box',
        description: 'A selection of 12 artisanal macarons: Salted Caramel, Matcha, Rose, Lemon, Blueberry, and Lavender.',
        price: 24.00,
        discountPercentage: 5,
        rating: 4.9,
        stock: 15,
        brand: 'TMPASTAHOUSE',
        category: 'Desserts',
        thumbnail: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=800'],
        tags: ['macarons', 'gift', 'dessert'],
    },
    {
        id: 1005,
        title: 'Red Velvet Royale Cupcake',
        description: 'Velvety red cocoa cake with a hint of vanilla, topped with our signature tangy cream cheese frosting.',
        price: 4.50,
        discountPercentage: 0,
        rating: 4.6,
        stock: 40,
        brand: 'TMPASTAHOUSE',
        category: 'Bakery',
        thumbnail: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?q=80&w=800'],
        tags: ['red-velvet', 'cupcake', 'bakery'],
    },
    {
        id: 1006,
        title: 'Lemon Meringue Tart',
        description: 'Buttery shortcrust pastry filled with zesty lemon curd and topped with toasted Swiss meringue peaks.',
        price: 7.25,
        discountPercentage: 20,
        rating: 4.8,
        stock: 10,
        brand: 'TMPASTAHOUSE',
        category: 'Pastries',
        thumbnail: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1519915028121-7d3463d20b13?q=80&w=800'],
        tags: ['lemon', 'tart', 'pastry'],
    },
    {
        id: 1007,
        title: 'Caramel Pecan Cheesecake',
        description: 'New York style cheesecake topped with sea salt caramel and roasted pecan halves on a graham cracker crust.',
        price: 18.99,
        discountPercentage: 10,
        rating: 5.0,
        stock: 6,
        brand: 'TMPASTAHOUSE',
        category: 'Signature Cakes',
        thumbnail: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=800'],
        tags: ['cheesecake', 'caramel', 'cake'],
    },
    {
        id: 1008,
        title: 'Hazelnut Praline Éclair',
        description: 'Choux pastry filled with hazelnut praline cream, dipped in milk chocolate and topped with caramelized hazelnut bits.',
        price: 6.50,
        discountPercentage: 0,
        rating: 4.7,
        stock: 20,
        brand: 'TMPASTAHOUSE',
        category: 'Pastries',
        thumbnail: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?q=80&w=500',
        images: ['https://images.unsplash.com/photo-1621303837174-89787a7d4729?q=80&w=800'],
        tags: ['eclair', 'hazelnut', 'pastry'],
    }
]

export const MOCK_CATEGORIES: Category[] = [
    { slug: 'signature-cakes', name: 'Signature Cakes', url: '' },
    { slug: 'pastries', name: 'Pastries', url: '' },
    { slug: 'desserts', name: 'Desserts', url: '' },
    { slug: 'bakery', name: 'Bakery', url: '' },
]
